set define off
whenever sqlerror exit sql.sqlcode rollback

prompt Creating Knowledge Bot governance schema objects

declare
  procedure run_ddl(p_sql in clob) is
  begin
    execute immediate p_sql;
  exception
    when others then
      if sqlcode not in (-955, -1430, -2260, -2275) then
        raise;
      end if;
  end;
begin
  run_ddl(q'[
    create table channels (
      channel_id number generated by default on null as identity,
      slack_workspace_id varchar2(128),
      slack_channel_id varchar2(128),
      slack_channel_name varchar2(255) not null,
      display_name varchar2(255) not null,
      enabled_yn varchar2(1) default 'Y' not null,
      status varchar2(30) default 'ACTIVE' not null,
      source_folder_link varchar2(2000),
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint channels_pk primary key (channel_id),
      constraint channels_enabled_ck check (enabled_yn in ('Y','N')),
      constraint channels_status_ck check (status in ('ACTIVE','DISABLED','PENDING','ERROR')),
      constraint channels_slack_name_uk unique (slack_channel_name)
    )
  ]');

  run_ddl(q'[create unique index channels_slack_id_uk on channels(slack_channel_id)]');

  run_ddl(q'[
    create table knowledge_sources (
      knowledge_source_id number generated by default on null as identity,
      source_key varchar2(255) not null,
      name varchar2(255) not null,
      source_type varchar2(50) default 'JSON_BUNDLE' not null,
      source_folder_link varchar2(2000),
      knowledge_bundle_path varchar2(2000),
      current_bundle_version varchar2(80),
      last_loaded_at timestamp with time zone,
      document_count number default 0 not null,
      chunk_count number default 0 not null,
      validation_status varchar2(30) default 'PENDING' not null,
      metadata_json clob,
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint knowledge_sources_pk primary key (knowledge_source_id),
      constraint knowledge_sources_key_uk unique (source_key),
      constraint knowledge_sources_type_ck check (source_type in ('JSON_BUNDLE','SQLITE','POSTGRES','OCI_OBJECT_STORAGE','SHAREPOINT_FILE')),
      constraint knowledge_sources_valid_ck check (validation_status in ('READY','PENDING','INVALID','ERROR')),
      constraint knowledge_sources_metadata_json_ck check (metadata_json is json)
    )
  ]');

  run_ddl(q'[
    create table knowledge_bundle_versions (
      bundle_version_id number generated by default on null as identity,
      knowledge_source_id number not null,
      bundle_id varchar2(255),
      bundle_version varchar2(80),
      checksum varchar2(128),
      generated_at timestamp with time zone,
      document_count number default 0 not null,
      chunk_count number default 0 not null,
      excluded_count number default 0 not null,
      validation_status varchar2(30) default 'PENDING' not null,
      metadata_json clob,
      created_at timestamp with time zone default systimestamp not null,
      constraint knowledge_bundle_versions_pk primary key (bundle_version_id),
      constraint kbv_source_fk foreign key (knowledge_source_id) references knowledge_sources(knowledge_source_id),
      constraint kbv_metadata_json_ck check (metadata_json is json)
    )
  ]');

  run_ddl(q'[
    create table guardrail_profiles (
      guardrail_profile_id number generated by default on null as identity,
      profile_key varchar2(255) not null,
      name varchar2(255) not null,
      system_guardrails clob not null,
      checkbox_defaults_json clob,
      additional_guardrails clob,
      require_sources_yn varchar2(1) default 'Y' not null,
      require_confidence_yn varchar2(1) default 'Y' not null,
      enabled_yn varchar2(1) default 'Y' not null,
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint guardrail_profiles_pk primary key (guardrail_profile_id),
      constraint guardrail_profiles_key_uk unique (profile_key),
      constraint guardrail_profiles_system_json_ck check (system_guardrails is json),
      constraint guardrail_profiles_checkbox_json_ck check (checkbox_defaults_json is json),
      constraint guardrail_profiles_bool_ck check (
        require_sources_yn in ('Y','N') and require_confidence_yn in ('Y','N') and enabled_yn in ('Y','N')
      )
    )
  ]');

  run_ddl(q'[
    create table analytics_sources (
      analytics_source_id number generated by default on null as identity,
      source_key varchar2(255) not null,
      name varchar2(255) not null,
      source_type varchar2(50) default 'APEX_TABLES' not null,
      location varchar2(2000),
      enabled_yn varchar2(1) default 'Y' not null,
      metadata_json clob,
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint analytics_sources_pk primary key (analytics_source_id),
      constraint analytics_sources_key_uk unique (source_key),
      constraint analytics_sources_type_ck check (source_type in ('APEX_TABLES','JSONL_FILE','SQLITE','POSTGRES','OCI_DB')),
      constraint analytics_sources_enabled_ck check (enabled_yn in ('Y','N')),
      constraint analytics_sources_metadata_json_ck check (metadata_json is json)
    )
  ]');

  run_ddl(q'[
    create table runner_pools (
      runner_pool_id number generated by default on null as identity,
      pool_key varchar2(255) not null,
      name varchar2(255) not null,
      runner_mode varchar2(50) default 'SHARED_RUNNER' not null,
      status varchar2(30) default 'ACTIVE' not null,
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint runner_pools_pk primary key (runner_pool_id),
      constraint runner_pools_key_uk unique (pool_key),
      constraint runner_pools_mode_ck check (runner_mode in ('SHARED_RUNNER','TEAM_RUNNER','USER_RUNNER','CLOUD_OR_SHARED_RUNNER')),
      constraint runner_pools_status_ck check (status in ('ACTIVE','DISABLED','ERROR'))
    )
  ]');

  run_ddl(q'[
    create table runners (
      runner_id number generated by default on null as identity,
      runner_pool_id number not null,
      runner_key varchar2(255) not null,
      name varchar2(255) not null,
      machine_id varchar2(255),
      owner_user_id varchar2(255),
      runner_type varchar2(30) default 'CLI' not null,
      platform varchar2(30),
      app_version varchar2(80),
      status varchar2(30) default 'OFFLINE' not null,
      codex_available_yn varchar2(1) default 'N' not null,
      codex_version varchar2(255),
      last_heartbeat_at timestamp with time zone,
      metadata_json clob,
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint runners_pk primary key (runner_id),
      constraint runners_key_uk unique (runner_key),
      constraint runners_pool_fk foreign key (runner_pool_id) references runner_pools(runner_pool_id),
      constraint runners_status_ck check (status in ('ONLINE','OFFLINE','BUSY','ERROR')),
      constraint runners_codex_ck check (codex_available_yn in ('Y','N')),
      constraint runners_metadata_json_ck check (metadata_json is json)
    )
  ]');

  run_ddl(q'[
    create table channel_configs (
      channel_config_id number generated by default on null as identity,
      channel_id number not null,
      knowledge_source_id number not null,
      guardrail_profile_id number not null,
      analytics_source_id number not null,
      runner_pool_id number not null,
      answer_style varchar2(80) default 'slack-threaded' not null,
      requires_local_runner_yn varchar2(1) default 'Y' not null,
      analytics_scope varchar2(50) default 'CHANNEL' not null,
      enabled_yn varchar2(1) default 'Y' not null,
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint channel_configs_pk primary key (channel_config_id),
      constraint channel_configs_channel_uk unique (channel_id),
      constraint channel_configs_channel_fk foreign key (channel_id) references channels(channel_id),
      constraint channel_configs_ks_fk foreign key (knowledge_source_id) references knowledge_sources(knowledge_source_id),
      constraint channel_configs_gp_fk foreign key (guardrail_profile_id) references guardrail_profiles(guardrail_profile_id),
      constraint channel_configs_as_fk foreign key (analytics_source_id) references analytics_sources(analytics_source_id),
      constraint channel_configs_rp_fk foreign key (runner_pool_id) references runner_pools(runner_pool_id),
      constraint channel_configs_bool_ck check (requires_local_runner_yn in ('Y','N') and enabled_yn in ('Y','N'))
    )
  ]');

  run_ddl(q'[
    create table question_logs (
      question_log_id number generated by default on null as identity,
      channel_id number,
      channel_config_id number,
      knowledge_source_id number,
      guardrail_profile_id number,
      slack_workspace_id varchar2(128),
      slack_channel_id varchar2(128),
      slack_user_id varchar2(128),
      slack_message_ts varchar2(80),
      question clob not null,
      normalized_question varchar2(2000),
      question_hash varchar2(128),
      answer clob,
      confidence_score number,
      confidence_level varchar2(30),
      response_time_ms number,
      codex_used_yn varchar2(1) default 'N' not null,
      cache_hit_yn varchar2(1) default 'N' not null,
      runner_id number,
      sources_json clob,
      retrieved_chunk_ids_json clob,
      created_at timestamp with time zone default systimestamp not null,
      constraint question_logs_pk primary key (question_log_id),
      constraint question_logs_channel_fk foreign key (channel_id) references channels(channel_id),
      constraint question_logs_config_fk foreign key (channel_config_id) references channel_configs(channel_config_id),
      constraint question_logs_ks_fk foreign key (knowledge_source_id) references knowledge_sources(knowledge_source_id),
      constraint question_logs_gp_fk foreign key (guardrail_profile_id) references guardrail_profiles(guardrail_profile_id),
      constraint question_logs_runner_fk foreign key (runner_id) references runners(runner_id),
      constraint question_logs_bool_ck check (codex_used_yn in ('Y','N') and cache_hit_yn in ('Y','N')),
      constraint question_logs_sources_json_ck check (sources_json is json),
      constraint question_logs_chunks_json_ck check (retrieved_chunk_ids_json is json)
    )
  ]');

  run_ddl(q'[
    create table answer_logs (
      answer_log_id number generated by default on null as identity,
      question_log_id number not null,
      answer clob not null,
      confidence_score number,
      confidence_level varchar2(30),
      codex_used_yn varchar2(1) default 'N' not null,
      cache_hit_yn varchar2(1) default 'N' not null,
      created_at timestamp with time zone default systimestamp not null,
      constraint answer_logs_pk primary key (answer_log_id),
      constraint answer_logs_question_fk foreign key (question_log_id) references question_logs(question_log_id) on delete cascade
    )
  ]');

  run_ddl(q'[
    create table source_usage (
      source_usage_id number generated by default on null as identity,
      question_log_id number,
      knowledge_source_id number,
      document_name varchar2(500),
      relative_path varchar2(2000),
      chunk_id varchar2(255),
      relevance_score number,
      source_quality varchar2(30),
      created_at timestamp with time zone default systimestamp not null,
      constraint source_usage_pk primary key (source_usage_id),
      constraint source_usage_question_fk foreign key (question_log_id) references question_logs(question_log_id) on delete cascade,
      constraint source_usage_ks_fk foreign key (knowledge_source_id) references knowledge_sources(knowledge_source_id)
    )
  ]');

  run_ddl(q'[
    create table analytics_events (
      analytics_event_id number generated by default on null as identity,
      channel_id number,
      channel_config_id number,
      knowledge_source_id number,
      analytics_source_id number,
      event_type varchar2(80) default 'QUESTION_ANSWER' not null,
      event_json clob not null,
      error_message varchar2(4000),
      created_at timestamp with time zone default systimestamp not null,
      constraint analytics_events_pk primary key (analytics_event_id),
      constraint analytics_events_channel_fk foreign key (channel_id) references channels(channel_id),
      constraint analytics_events_config_fk foreign key (channel_config_id) references channel_configs(channel_config_id),
      constraint analytics_events_ks_fk foreign key (knowledge_source_id) references knowledge_sources(knowledge_source_id),
      constraint analytics_events_as_fk foreign key (analytics_source_id) references analytics_sources(analytics_source_id),
      constraint analytics_events_json_ck check (event_json is json)
    )
  ]');

  run_ddl(q'[
    create table system_settings (
      setting_key varchar2(255) not null,
      setting_value varchar2(4000),
      value_type varchar2(30) default 'STRING' not null,
      is_secret_yn varchar2(1) default 'N' not null,
      description varchar2(2000),
      created_at timestamp with time zone default systimestamp not null,
      updated_at timestamp with time zone default systimestamp not null,
      constraint system_settings_pk primary key (setting_key),
      constraint system_settings_secret_ck check (is_secret_yn in ('Y','N'))
    )
  ]');

  run_ddl(q'[
    create table audit_logs (
      audit_log_id number generated by default on null as identity,
      entity_type varchar2(80) not null,
      entity_id varchar2(255),
      action varchar2(80) not null,
      changed_by varchar2(255) default coalesce(sys_context('APEX$SESSION','APP_USER'), user),
      before_json clob,
      after_json clob,
      created_at timestamp with time zone default systimestamp not null,
      constraint audit_logs_pk primary key (audit_log_id),
      constraint audit_logs_before_json_ck check (before_json is json),
      constraint audit_logs_after_json_ck check (after_json is json)
    )
  ]');

  run_ddl(q'[create index channel_configs_ks_ix on channel_configs(knowledge_source_id)]');
  run_ddl(q'[create index question_logs_created_ix on question_logs(created_at)]');
  run_ddl(q'[create index question_logs_channel_ix on question_logs(channel_id, created_at)]');
  run_ddl(q'[create index analytics_events_created_ix on analytics_events(created_at)]');
  run_ddl(q'[create index runners_status_ix on runners(status, last_heartbeat_at)]');
end;
/

create or replace trigger channels_biu
before insert or update on channels
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace trigger knowledge_sources_biu
before insert or update on knowledge_sources
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace trigger guardrail_profiles_biu
before insert or update on guardrail_profiles
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace trigger runners_biu
before insert or update on runners
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace trigger channel_configs_biu
before insert or update on channel_configs
for each row
begin
  :new.updated_at := systimestamp;
end;
/

create or replace view kb_channel_config_v as
select
  cc.channel_config_id,
  c.channel_id,
  c.slack_workspace_id,
  c.slack_channel_id,
  c.slack_channel_name,
  c.display_name channel_display_name,
  c.enabled_yn channel_enabled_yn,
  c.status channel_status,
  c.source_folder_link,
  ks.knowledge_source_id,
  ks.source_key knowledge_source_key,
  ks.name knowledge_source_name,
  ks.source_type knowledge_source_type,
  ks.knowledge_bundle_path,
  ks.current_bundle_version,
  ks.last_loaded_at,
  ks.document_count,
  ks.chunk_count,
  ks.validation_status knowledge_validation_status,
  gp.guardrail_profile_id,
  gp.profile_key guardrail_profile_key,
  gp.name guardrail_profile_name,
  gp.system_guardrails,
  gp.checkbox_defaults_json,
  gp.additional_guardrails,
  gp.require_sources_yn,
  gp.require_confidence_yn,
  rp.runner_pool_id,
  rp.pool_key runner_pool_key,
  rp.name runner_pool_name,
  rp.runner_mode runner_pool_mode,
  ans.analytics_source_id,
  ans.source_key analytics_source_key,
  ans.name analytics_source_name,
  cc.answer_style,
  cc.requires_local_runner_yn,
  cc.analytics_scope,
  cc.enabled_yn config_enabled_yn,
  cc.updated_at config_updated_at
from channel_configs cc
join channels c on c.channel_id = cc.channel_id
join knowledge_sources ks on ks.knowledge_source_id = cc.knowledge_source_id
join guardrail_profiles gp on gp.guardrail_profile_id = cc.guardrail_profile_id
join runner_pools rp on rp.runner_pool_id = cc.runner_pool_id
join analytics_sources ans on ans.analytics_source_id = cc.analytics_source_id;

create or replace view kb_dashboard_v as
select
  (select count(*) from channels) total_channels,
  (select count(*) from channels where enabled_yn = 'Y') enabled_channels,
  (select count(*) from knowledge_sources) total_knowledge_sources,
  (select count(*) from question_logs) total_questions,
  (select count(*) from analytics_events) total_analytics_events,
  (select count(*) from runners where status = 'ONLINE') online_runners,
  (select count(*) from runners where codex_available_yn = 'Y') codex_available_runners,
  (select max(created_at) from question_logs) latest_question_at,
  (select max(last_heartbeat_at) from runners) latest_runner_heartbeat_at
from dual;

create or replace view kb_question_history_v as
select
  q.question_log_id,
  c.display_name channel_name,
  ks.name knowledge_source_name,
  gp.name guardrail_profile_name,
  dbms_lob.substr(q.question, 2000, 1) question,
  dbms_lob.substr(q.answer, 4000, 1) answer_preview,
  q.confidence_score,
  q.confidence_level,
  q.response_time_ms,
  q.codex_used_yn,
  q.cache_hit_yn,
  q.created_at,
  q.sources_json
from question_logs q
left join channels c on c.channel_id = q.channel_id
left join knowledge_sources ks on ks.knowledge_source_id = q.knowledge_source_id
left join guardrail_profiles gp on gp.guardrail_profile_id = q.guardrail_profile_id;

create or replace view kb_runner_status_v as
select
  rp.name runner_pool_name,
  rp.runner_mode runner_pool_mode,
  r.runner_id,
  r.runner_key,
  r.name runner_name,
  r.runner_type,
  r.platform,
  r.status,
  r.codex_available_yn,
  r.codex_version,
  r.last_heartbeat_at,
  r.updated_at
from runner_pools rp
left join runners r on r.runner_pool_id = rp.runner_pool_id;

create or replace view kb_analytics_summary_v as
select
  trunc(cast(created_at as timestamp)) event_day,
  count(*) total_events,
  sum(case when json_value(event_json, '$.cacheHit') = 'true' then 1 else 0 end) cache_hits,
  avg(to_number(nullif(json_value(event_json, '$.responseTimeMs'), ''))) avg_response_time_ms
from analytics_events
group by trunc(cast(created_at as timestamp));

merge into knowledge_sources t
using (
  select
    'einvoicing-bundle' source_key,
    'E-Invoice Knowledge Bundle' name,
    'JSON_BUNDLE' source_type,
    'local/synced E-Invoice source' source_folder_link,
    './data/e-invoicing-knowledge-bundle.json' knowledge_bundle_path,
    '1.0.0' current_bundle_version,
    96 document_count,
    989 chunk_count,
    'READY' validation_status
  from dual
) s
on (t.source_key = s.source_key)
when matched then update set
  t.name = s.name,
  t.source_type = s.source_type,
  t.source_folder_link = s.source_folder_link,
  t.knowledge_bundle_path = s.knowledge_bundle_path,
  t.current_bundle_version = s.current_bundle_version,
  t.document_count = s.document_count,
  t.chunk_count = s.chunk_count,
  t.validation_status = s.validation_status,
  t.last_loaded_at = coalesce(t.last_loaded_at, systimestamp)
when not matched then insert (
  source_key, name, source_type, source_folder_link, knowledge_bundle_path,
  current_bundle_version, document_count, chunk_count, validation_status, last_loaded_at, metadata_json
) values (
  s.source_key, s.name, s.source_type, s.source_folder_link, s.knowledge_bundle_path,
  s.current_bundle_version, s.document_count, s.chunk_count, s.validation_status, systimestamp,
  json_object('seeded' value true)
);

merge into guardrail_profiles t
using (
  select
    'strict-document-only' profile_key,
    'Strict Document Only' name,
    json_array(
      'Answer only from the approved knowledge bundle context.',
      'Do not browse the internet.',
      'Do not speculate or use unsupported external knowledge.',
      'If information is missing, say it is not available in the approved knowledge source.',
      'Include sources and confidence.'
      returning clob
    ) system_guardrails,
    json_object(
      'sourceOnly' value true,
      'noInternet' value true,
      'includeSources' value true,
      'includeConfidence' value true
      returning clob
    ) checkbox_defaults_json,
    'Use concise, business-readable answers. Preserve qualifiers separately from entities when relevant.' additional_guardrails
  from dual
) s
on (t.profile_key = s.profile_key)
when matched then update set
  t.name = s.name,
  t.system_guardrails = s.system_guardrails,
  t.checkbox_defaults_json = s.checkbox_defaults_json,
  t.additional_guardrails = s.additional_guardrails
when not matched then insert (
  profile_key, name, system_guardrails, checkbox_defaults_json, additional_guardrails
) values (
  s.profile_key, s.name, s.system_guardrails, s.checkbox_defaults_json, s.additional_guardrails
);

merge into analytics_sources t
using (select 'apex-analytics' source_key, 'APEX Analytics Tables' name, 'APEX_TABLES' source_type from dual) s
on (t.source_key = s.source_key)
when matched then update set t.name = s.name, t.source_type = s.source_type
when not matched then insert (source_key, name, source_type, location, metadata_json)
values (s.source_key, s.name, s.source_type, 'LOCAL_CODEX.ANALYTICS_EVENTS', json_object('seeded' value true));

merge into runner_pools t
using (select 'default-codex-runner-pool' pool_key, 'Default Codex Runner Pool' name, 'CLOUD_OR_SHARED_RUNNER' runner_mode from dual) s
on (t.pool_key = s.pool_key)
when matched then update set t.name = s.name, t.runner_mode = s.runner_mode
when not matched then insert (pool_key, name, runner_mode)
values (s.pool_key, s.name, s.runner_mode);

merge into channels t
using (
  select
    'emea-e-invoice' slack_channel_name,
    'EMEA-E-invoice' display_name,
    'Y' enabled_yn,
    'ACTIVE' status,
    'local/synced E-Invoice source' source_folder_link
  from dual
) s
on (t.slack_channel_name = s.slack_channel_name)
when matched then update set
  t.display_name = s.display_name,
  t.enabled_yn = s.enabled_yn,
  t.status = s.status,
  t.source_folder_link = s.source_folder_link
when not matched then insert (slack_channel_name, display_name, enabled_yn, status, source_folder_link)
values (s.slack_channel_name, s.display_name, s.enabled_yn, s.status, s.source_folder_link);

merge into channel_configs t
using (
  select
    c.channel_id,
    ks.knowledge_source_id,
    gp.guardrail_profile_id,
    ans.analytics_source_id,
    rp.runner_pool_id
  from channels c
  cross join knowledge_sources ks
  cross join guardrail_profiles gp
  cross join analytics_sources ans
  cross join runner_pools rp
  where c.slack_channel_name = 'emea-e-invoice'
    and ks.source_key = 'einvoicing-bundle'
    and gp.profile_key = 'strict-document-only'
    and ans.source_key = 'apex-analytics'
    and rp.pool_key = 'default-codex-runner-pool'
) s
on (t.channel_id = s.channel_id)
when matched then update set
  t.knowledge_source_id = s.knowledge_source_id,
  t.guardrail_profile_id = s.guardrail_profile_id,
  t.analytics_source_id = s.analytics_source_id,
  t.runner_pool_id = s.runner_pool_id,
  t.answer_style = 'slack-threaded',
  t.requires_local_runner_yn = 'Y',
  t.analytics_scope = 'CHANNEL',
  t.enabled_yn = 'Y'
when not matched then insert (
  channel_id, knowledge_source_id, guardrail_profile_id, analytics_source_id,
  runner_pool_id, answer_style, requires_local_runner_yn, analytics_scope, enabled_yn
) values (
  s.channel_id, s.knowledge_source_id, s.guardrail_profile_id, s.analytics_source_id,
  s.runner_pool_id, 'slack-threaded', 'Y', 'CHANNEL', 'Y'
);

merge into runners t
using (
  select
    rp.runner_pool_id,
    'local-shared-runner' runner_key,
    'Local Shared Codex Runner' name
  from runner_pools rp
  where rp.pool_key = 'default-codex-runner-pool'
) s
on (t.runner_key = s.runner_key)
when matched then update set
  t.runner_pool_id = s.runner_pool_id,
  t.name = s.name
when not matched then insert (
  runner_pool_id, runner_key, name, runner_type, platform, status, codex_available_yn, metadata_json
) values (
  s.runner_pool_id, s.runner_key, s.name, 'CLI', 'LOCAL', 'OFFLINE', 'N', json_object('seeded' value true)
);

merge into system_settings t
using (
  select 'DEPLOYMENT_MODE' setting_key, 'LOCAL' setting_value, 'STRING' value_type, 'Current deployment runner_mode.' description from dual union all
  select 'BACKEND_MODE', 'APEX', 'STRING', 'Slack runtime should use APEX/ORDS as backend.' from dual union all
  select 'BOT_CONFIG_REFRESH_INTERVAL_HOURS', '24', 'NUMBER', 'Configuration refresh interval.' from dual union all
  select 'ENABLE_MSAL_GRAPH', 'false', 'BOOLEAN', 'Future Microsoft Graph integration flag.' from dual
) s
on (t.setting_key = s.setting_key)
when matched then update set t.setting_value = s.setting_value, t.value_type = s.value_type, t.description = s.description
when not matched then insert (setting_key, setting_value, value_type, description)
values (s.setting_key, s.setting_value, s.value_type, s.description);

commit;

prompt Knowledge Bot governance schema complete
